name: AdvancedSpyInventory
author: DailyCraft
description: Open and modify the inventory of entities and players, online or not ! But you can also modify the ender chest of the players
version: 1.4
website: https://dev.bukkit.org/projects/advancedspyinventory
main: minecraft.dailycraft.advancedspyinventory.Main

commands:
  inventory:
    description: Open inventory of players or entities
    usage: /<command> <Player|Entity>
    permission: advancedspyinventory.inventory
    aliases:
      - inv
      - i

  enderchest:
    description: Open ender chest of players
    usage: /<command> [Player]
    permission: advancedspyinventory.enderchest
    aliases:
      - ec
      - e