name: AdvancedSpyInventory
author: DailyCraft
description: Open inventory and ender chest of other players, online or not !
version: 1.3
main: minecraft.dailycraft.advancedspyinventory.Main

commands:
  inventory:
    description: Open inventory of players
    usage: /inv <Player>
    permission: advancedspyinventory.inventory.use
    aliases: inv

  enderchest:
    description: Open ender chest of players
    usage: /enderchest [Player]
    permission: advancedspyinventory.enderchest.use
    aliases:
      - ec
      - e